#!/bin/sh

case "$1" in
  start)
    printf "Launching Snes9x (Ultra-Fast Boot)...\n"
    
    # Drivers ya cargados por modules-load.d/vc4.conf
    
    # Entorno SDL para GPU
    export SDL_VIDEODRIVER=kmsdrm
    export SDL_RENDER_DRIVER=opengles2
    export SDL_RENDER_VSYNC=1
    export HOME=/root
    
    # Lanzar el emulador inmediatamente en segundo plano
    # Esto permite que el sistema siga arrancando el Bluetooth/WiFi mientras juegas
    cd /root
    /usr/bin/snes9x >/var/log/snes9x.log 2>&1 &
    ;;
    
  stop)
    killall snes9x 2>/dev/null
    ;;
    
  restart|reload)
    "$0" stop
    sleep 1
    "$0" start
    ;;
    
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
