#!/bin/sh

case "$1" in
  start)
    printf "Launching Snes9x (Ultra-Fast Boot)...\n"
    
    # Drivers already loaded by modules-load.d/vc4.conf
    
    # SDL environment for GPU
    export SDL_VIDEODRIVER=kmsdrm
    export SDL_RENDER_DRIVER=opengles2
    export SDL_RENDER_VSYNC=1
    export HOME=/root
    
    # Launch the emulator immediately in the background
    # This allows the system to continue booting Bluetooth/WiFi while you play
    cd /root
    /usr/bin/snes9x -aspect-ratio 8:7 >/var/log/snes9x.log 2>&1 &
    ;;
    
  stop)
    killall snes9x 2>/dev/null
    ;;
    
  restart|reload)
    "$0" stop
    sleep 1
    "$0" start
    ;;
    
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
