#!/bin/sh
#
# S99background - Start background services (WiFi, Bluetooth, SSH)
#

case "$1" in
  start)
    # Give system time to initialize
    sleep 3
    
    printf "Starting background services...\n"
    
    # Initialize Bluetooth hardware on mini-UART (ttyS0)
    printf "Initializing Bluetooth...\n"
    hciattach /dev/ttyS0 bcm43xx 460800 noflow - 2>/dev/null &
    sleep 1.5
    
    # Start Bluetooth daemon
    /usr/libexec/bluetooth/bluetoothd &
    sleep 1
    
    # Connect WiFi
    printf "Connecting to WiFi...\n"
    wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf 2>/dev/null
    udhcpc -i wlan0 -b -q -n 2>/dev/null &
    
    # Start Avahi for zero.local mDNS resolution
    printf "Starting Avahi daemon...\n"
    /usr/sbin/avahi-daemon -D 2>/dev/null
    
    # Start SSH daemon
    printf "Starting SSH server...\n"
    /etc/init.d/S50dropbear start 2>/dev/null
    
    # Set hostname
    hostname zero
    
    printf "Background services initialized.\n"
    ;;
    
  stop)
    /usr/sbin/avahi-daemon -k 2>/dev/null
    killall bluetoothd 2>/dev/null
    killall wpa_supplicant 2>/dev/null
    /etc/init.d/S50dropbear stop 2>/dev/null
    ;;
    
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
