#!/bin/sh
#
# S99emulator - Launch Snes9x emulator after all services are ready
#

case "$1" in
  start)
    printf "Starting Snes9x emulator...\n"
    
    # Load required drivers
    printf "Loading drivers (I2C, Sound, DRM)...\n"
    modprobe i2c-bcm2835 2>/dev/null
    modprobe i2c-dev 2>/dev/null
    modprobe snd-bcm2835 2>/dev/null
    modprobe drm 2>/dev/null
    modprobe vc4 2>/dev/null
    
    # Wait for DRM devices to be ready
    sleep 5
    
    # Start background services if not already running
    if [ ! -f /var/run/emulator_bg.started ]; then
        /etc/init.d/S99background start &
        touch /var/run/emulator_bg.started
    fi
    
    # Set SDL environment variables
    export SDL_VIDEODRIVER=kmsdrm
    export SDL_RENDER_DRIVER=opengles2
    export SDL_RENDER_VSYNC=1
    
    # Launch emulator with the correct ROM path
    cd /root
    /usr/bin/snes9x "/root/.snes9x/rom/Super Mario World (USA).zip" >/var/log/snes9x.log 2>&1 &
    
    printf "Snes9x started.\n"
    ;;
    
  stop)
    printf "Stopping Snes9x...\n"
    killall snes9x 2>/dev/null
    rm -f /var/run/emulator_bg.started
    ;;
    
  restart|reload)
    "$0" stop
    sleep 2
    "$0" start
    ;;
    
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
