# Configuration file for the input service

[General]

# Set idle timeout (in seconds) before the connection will be disconnect
# Defaults: 0 (disabled)
IdleTimeout=0

# Enable HID protocol handling in userspace input profile
# Defaults to true
UserspaceHID=false

# Limit HID connections to bonded devices
# Set to false to allow connections from non-bonded devices (like Nintendo controllers)
# Defaults to true for security.
ClassicBondedOnly=false

# LE upgrade security
# Enables upgrades of security automatically if required.
# Defaults to true to maximize device compatibility.
LEAutoSecurity=false
