[General]
Name = zero.local
Class = 0x000540
DiscoverableTimeout = 0
PairableTimeout = 0
Discoverable = true
Pairable = true
AutoEnable = true
ControllerMode = dual

[Policy]
AutoEnable = true
ReconnectAttempts = 7
ReconnectIntervals = 1,2,4,8,16,32,64

[GATT]
Cache = yes
KeySize = 16

[AVDTP]
SessionMode = ertm

[LE]
MinConnectionInterval = 7
MaxConnectionInterval = 9
ConnectionLatency = 0
ConnectionSupervisionTimeout = 100
